# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: micro_basics.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'micro_basics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12micro_basics.proto\x12\x0cmicro_basics\"\x07\n\x05\x45mpty\"\x1c\n\x08Messages\x12\x10\n\x08messages\x18\x01 \x03(\t\"(\n\x07Message\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0bstatus_code\x18\x02 \x01(\x05\x32{\n\x0eLoggingService\x12\x32\n\x03Get\x12\x13.micro_basics.Empty\x1a\x16.micro_basics.Messages\x12\x35\n\x04Post\x12\x15.micro_basics.Message\x1a\x16.micro_basics.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'micro_basics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=36
  _globals['_EMPTY']._serialized_end=43
  _globals['_MESSAGES']._serialized_start=45
  _globals['_MESSAGES']._serialized_end=73
  _globals['_MESSAGE']._serialized_start=75
  _globals['_MESSAGE']._serialized_end=115
  _globals['_RESPONSE']._serialized_start=117
  _globals['_RESPONSE']._serialized_end=165
  _globals['_LOGGINGSERVICE']._serialized_start=167
  _globals['_LOGGINGSERVICE']._serialized_end=290
# @@protoc_insertion_point(module_scope)
